version: '3'
services:
  db:
    image: postgres:9.4.5
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports: 
      - "5432:5432"
    networks: 
      - demo-network
  backend:
    image: marcelormourao/backend
    ports: 
      - "8080:8080"
    networks: 
      - demo-network
    depends_on:
      - db
  frontend:
    image: marcelormourao/frontend
    ports: 
      - "80:80"
    networks: 
      - demo-network
    depends_on: 
      - backend
networks: 
  demo-network:
    driver: bridge